version: '3.8'

services:
  kiro-api:
    image: gua12345/kiro2api:rs
    container_name: kiro-api-container
    ports:
      - "8990:8990"
    volumes:
      - ./config:/app/config
    restart: unless-stopped